notifications:
  webhooks:
    - https://webhook.commit-email.info/

sudo: required

services:
  - docker

install:
  - docker build -t red-data-tools/red-datasets-arrow .

script:
  - docker run red-data-tools/red-datasets-arrow /bin/sh -c "bundle exec rake"
