name: Test

on:
  - push
  - pull_request

jobs:
  test:
    name: "Ruby ${{ matrix.ruby-version }}: ${{ matrix.runs-on }}"
    strategy:
      # To avoid high frequency datasets download in a short time.
      max-parallel: 1
      fail-fast: false
      matrix:
        ruby-version:
          - "2.6"
          - "2.7"
          - "3.0"
        runs-on:
          # - macos-latest
          - ubuntu-latest
          # - windows-latest
    runs-on: ${{ matrix.runs-on }}
    steps:
      - uses: actions/checkout@v2
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby-version }}
      - uses: actions/cache@v2
        if: |
          runner.os == 'Linux'
        with:
          path: |
            ~/.cache/red-datasets
          key: ${{ runner.os }}-${{ hashFiles('lib/**') }}
          restore-keys: |
            ${{ runner.os }}-
      - uses: actions/cache@v2
        if: |
          runner.os == 'macOS'
        with:
          path: |
            ~/Library/Caches/red-datasets
          key: ${{ runner.os }}-${{ hashFiles('lib/**') }}
          restore-keys: |
            ${{ runner.os }}-
      - uses: actions/cache@v2
        if: |
          runner.os == 'Windows'
        with:
          path: |
            ~/AppData/Local/red-datasets
          key: ${{ runner.os }}-${{ hashFiles('lib/**') }}
          restore-keys: |
            ${{ runner.os }}-
      - name: Prepare the Apache Arrow APT repository
        if: |
          runner.os == 'Linux'
        run: |
          sudo apt update
          sudo apt install -y -V ca-certificates lsb-release wget
          wget https://apache.jfrog.io/artifactory/arrow/$(lsb_release --id --short | tr 'A-Z' 'a-z')/apache-arrow-apt-source-latest-$(lsb_release --codename --short).deb
          sudo apt install -y -V ./apache-arrow-apt-source-latest-$(lsb_release --codename --short).deb
          sudo apt update
      - name: Install dependencies
        run: |
          bundle install
      - name: Test
        run: |
          bundle exec rake
